### PR TITLE
Updates the main reggie python file name

### PR DESCRIPTION
**Pull request by zzolo**
This is a minor fix to help with import name collisions that I ran into.

The basic issue is that because there was a `reggie.py` inside the `reggie` package, it caused some issues with importing in Python since Python treats an import like it could be a package, a module/file, or a method (depending on how the import statement is formed).

Reference:
https://docs.python.org/3/tutorial/modules.html#packages

### CODE REVIEW

**Comment by cvcotton** [comment]
This should be fine, yeah.

I think you probably need to update setup.py where it has the alias for the command line usage "reg=reggie:convert_cli" to use main:convert_cli or else the command line usage in the readme may not work.

**Comment by zzolo** [comment]
This still works for me.  I think the with `reggie:convert_cli`, `reggie` refers to the the package, not the file.  Though to be honest, I am no expert here.

Reference:
https://setuptools.readthedocs.io/en/latest/userguide/entry_point.html

**Comment by cvcotton** [comment]
ok cool, as long as it works!

**Review by cvcotton — APPROVED** [review]
cool

**Pull request merged**
