### PR TITLE
Fix Colorado duplicate voter problem by removing all but 1 set of voter files

### PR DESCRIPTION
**Pull request by cvcotton**
This bug fix uses a few heuristics to remove older duplicate versions of voter files in Colorado:
- remove any voter files with "Public" in the file name (this was the original solution to the problem, but it alone fails in more recent cases)
- remove any voter files with previous years in the file path (e.g. "EX-003 Master Voter List/2020_June_Primary/Registered_Voters_List_Public_ Part2.txt")
- remove voter files that are not the highest up in the path hierarchy

In order to accomplish this, this PR also slightly changes the general unzip process for all file packages, and retains a full file path for all unzipped files. In practice, this means that all unzipped file names (in all states) will now have "/tmp/..." appended to the front of their unzipped file names. I have verified on a state-by-state basis that this should not actually affect any file-finding or file-processing in other states.

### CODE REVIEW

**Review by zzolo — APPROVED** [review]
This reads ok.  Is it possible to make some tests for this method?  Maybe it's too tied to S3?

**Comment by cvcotton** [comment]
> This reads ok. Is it possible to make some tests for this method? Maybe it's too tied to S3?

Yeah, that unzip_decompress() method is a method of the Preprocessor class itself. So I think for a test, we'd at least need a mock s3 file to instantiate the Preprocessor. If there are instructions somewhere for s3 file mocking I can try to do that?

**Comment by nicholastulach** [comment]
> If there are instructions somewhere for s3 file mocking I can try to do that? Also the mock file would have to be a zip package, if that's possible?

Moto has an [s3 mock](http://docs.getmoto.org/en/latest/docs/services/s3.html) package. Not sure if it supports zipped files, though.

**Comment by cvcotton** [comment]
I just added a simple fake zip file package and loaded it into a Preprocessor using the local file functionality, and just use that to test that the unzip produces files with the correct full paths. Easier than I thought / than worrying about moto would have been.

**Pull request merged**
